[2021-12-01 17:51:10,989] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-12-01T22:50:44.858833+00:00 [queued]>
[2021-12-01 17:51:10,995] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-12-01T22:50:44.858833+00:00 [queued]>
[2021-12-01 17:51:10,996] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 17:51:10,996] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-01 17:51:10,996] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 17:51:11,003] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): inaccurate> on 2021-12-01 22:50:44.858833+00:00
[2021-12-01 17:51:11,005] {standard_task_runner.py:52} INFO - Started process 54177 to run task
[2021-12-01 17:51:11,011] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2021-12-01T22:50:44.858833+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/var/folders/xt/_j47lzt57cj88vmq2807qx_00000gp/T/tmp_q23ygcp', '--error-file', '/var/folders/xt/_j47lzt57cj88vmq2807qx_00000gp/T/tmp8sgoux0d']
[2021-12-01 17:51:11,013] {standard_task_runner.py:77} INFO - Job 25: Subtask inaccurate
[2021-12-01 17:51:11,042] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2021-12-01T22:50:44.858833+00:00 [running]> on host zipcodes-macbook-pro-6.local
[2021-12-01 17:51:11,065] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T22:50:44.858833+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-01T22:50:44.858833+00:00
[2021-12-01 17:51:11,065] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/xt/_j47lzt57cj88vmq2807qx_00000gp/T
[2021-12-01 17:51:11,066] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-12-01 17:51:11,071] {subprocess.py:85} INFO - Output:
[2021-12-01 17:51:11,074] {subprocess.py:89} INFO - inaccurate
[2021-12-01 17:51:11,074] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-01 17:51:11,087] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20211201T225044, start_date=20211201T225110, end_date=20211201T225111
[2021-12-01 17:51:11,107] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-01 17:51:11,122] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
